# total
batch_size: 1

# encoder
have_time: False
time_series_length: 10

## img
have_img: True
channels: 3
img_size_x: 256
img_size_y: 256 
img_encoder: "Lenet"
## audio
have_audio: True
audio_init_file: "applications/customization/raw_data/audio.aac"
audio_encoder: "Librosa"

## text
have_text: False
text_init_file: "applications/customization/raw_data/text.txt"
text_encoder: "Bert"

## video
have_video: False
video_init_file: "applications/customization/raw_data/video.mp4"

## sensor
have_sensor: True
# sensor_length: 10
zdim: 128
have_action: True
action_dim: 4
have_proprio: False
proprio: 1.0
have_depth: False
depth: 1.0
have_force: False
force: 1.0

# fusion
fusion_type: "concat"

# head
head_type: "MLP"
input_dim: 571
hidden_dim: 128
output_dim: 1